#train & test dataset location
train_data_path: "data/train.csv"
test_data_path: "data/test.csv"

#model blueprint location and where to store the trained model and predictions
model_blueprint_path: "output/03_nn_modeling__exp_D.joblib"
model_trained_path : "models/03_nn_modeling__exp_D_trained.joblib"
preds_path: "output/preds/03_nn_modeling__exp_D_preds.csv"

#training parameters
target_col: "BeatsPerMinute"
feature_cols : [
  'RhythmScore',
  'AudioLoudness',
  'VocalContent',
  'AcousticQuality',
  'InstrumentalScore',
  'LivePerformanceLikelihood',
  'MoodScore',
  'TrackDurationMs',
  'Energy'
]